version: '2.2'
services:
  opensips-rec:
    image: qxip/docker-rtpengine-record
    privileged: true
    restart: always
    environment:
      ADVERTISED_RANGE_FIRST: 20000
      ADVERTISED_RANGE_LAST: 20100
      HOMER_SERVER: '127.0.0.1'
      HOMER_PORT: 9060
      BING_KEY: 'YOUR_KEY_HERE'
    volumes:
       - /var/lib/mysql
       - /recording
    ports:
      - "9060:9060/udp"
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "20000-20100:20000-20100/udp"
